name: CI
on: [pull_request]
jobs:
    unittest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Golang
              uses: actions/setup-go@v3
              with:
                go-version: 1.18
            - name: Tests
              run: make test
    linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Golang
              uses: actions/setup-go@v3
              with:
                go-version: 1.18
            - name: Golint
              uses: golangci/golangci-lint-action@v3
              with:
                version: latest
            
